### ISSUE TITLE
beta - Page navigation upgrades

### ISSUE THREAD

**Issue by xyzrus** [adamjberg/engram#107]
beta.engram.xyz Desktop/ all browsers- Events =

1) ~Note – cannot copy ALL page text, only 1 selected line at a time~ (Moved to #111)
~When pasting formatted text – all formatting is removed, putting all text in a long string~ (covered by #110)

2) ~while entering multiple notes: type last entry; click logo to refresh – return to eg = former last note appears in random order above, not on last space as entered or expected~  (Moved to #109)

3) ~typing at end of eg line, ENTER moves cursor to next line = no way to create multi-line Notes on Pages; cannot insert lines between any other already created lines~ (Moved to #110)

4) ~Children do not appear to have any function other than indent – can't do anything with them; cannot hide or expand content~ (#112)

**Comment by adamjberg** [comment]
Moved these to separate issues so some can be skipped for later.
