### ISSUE TITLE
Agenda view not pulling engrams created on selected Dates

### ISSUE THREAD

**Issue by xyzrus** [adamjberg/engram#85]
All desktop browsers: when viewing Daily engrams - switch to Agenda view = no engrams displayed.
Each Agenda Date should have a timeline history/record of engrams created for that date.

**Comment by adamjberg** [comment]
Ah, interesting.  I did this intentionally.  e.g. if you don't explicitly set a time to a task/note it doesn't show in the Agenda view.  I need to stew on what the best behaviour would be here and how to keep consistent.
